---
apiVersion: v1
kind: Template
labels:
  template: 'educ-ruleengine-api-template'
metadata:
  name: 'educ-ruleengine-api-template'
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: educ-ruleengine-api-pipeline
    name: educ-ruleengine-api-pipeline
    namespace: 77c02f-tools
  spec:
    source:
      git:
        ref: release/1.0.0
        uri: 'https://github.com/bcgov/EDUC-RULE-ENGINE-API'
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: tools/jenkins/Jenkinsfile-api
